apiVersion: apps/v1
kind: Deployment
metadata:
  name: dpl-yprovider
spec:
  replicas: 1
  selector:
    matchLabels:
      app: docs
      component: yprovider
  template:
    metadata:
      labels:
        app: docs
        component: yprovider
    spec:
      automountServiceAccountToken: false
      containers:
        - name: docs
          image: lasuite/impress-y-provider:v1.10.0
          env:
            - name: "COLLABORATION_LOGGING"
              value: "true"
            - name: "COLLABORATION_SERVER_ORIGIN"
              value: "https://docs.la-suite.apps.digilab.network"
            - name: "COLLABORATION_SERVER_SECRET"
              valueFrom:
                secretKeyRef:
                  name: sec-docs
                  key: server_secret
            - name: "Y_PROVIDER_API_KEY"
              value: "my-secret"
          ports:
            - name: http
              containerPort: 4444
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /ping
              port: 4444
            initialDelaySeconds: 10
            timeoutSeconds: 1
          resources:
            requests:
              cpu: 500m
              memory: 4Gi
              ephemeral-storage: "2Gi"
