apiVersion: v1
kind: Secret
metadata:
  name: sec-postgres-super
type: Opaque
stringData:
  password: ENC[AES256_GCM,data:c1ziTbdhDIQf3gkX2xJCI+d+,iv:sBsO+7MRbtzckS6ylzntzLwbim/efuJp3x6w8kECiCc=,tag:stYPtUVDiKwi1NGCBaTNlQ==,type:str]
  username: ENC[AES256_GCM,data:5ov1Xx+84lU=,iv:/PqoMyD/AS/AXlFRFAtbNdZeUPh0FnKn5NNKQvnjegg=,tag:9TVnPHRUv2gR+gYSjSfNig==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1xqm6rlmcsyfna0chsmf8gw64n86405rgr04ek5drad04ca00fewqp02n5c
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwNUlNWU1RYStib3oxNkU0
        VmZHN1N1eGlpYm5OcnM4aStCUHZDL2t5V1ZJCnhEL2xGN0Jqem03RWpEb0xjclFy
        d3htL2tvNlJDNElZWkI3KzZlamdoaXMKLS0tIGFMVFcyZHJNZENyTzNxZk00Qm5P
        K1BOSFo1ejV1SjJNR255K1IwZHI0SWMKN0nmNawlxqlC5h6IJgOp/Wu0/zsbgtbT
        lPdmVyErCKVtg4Lzx2CmQToLb95a6aIOdeaaShs9KjNl+fg9gDBgQA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2024-12-23T21:51:31Z"
  mac: ENC[AES256_GCM,data:rllkrE5cYFUkLQKH0tBQPKbd1tx7FGQtgP61rZAjm+sTLcSi7yyiQWIO7fOKwFzTZjC69UueJT1coPlgPuDsAnIcM8US4DKeGXk24cDjc3XUywQvru1DFbFfvbY/G5CkThwaQ6P0CR8Bs0RMS1gXk+O3LZlIvkyEvFt43DqgPSU=,iv:uh2lUTyh0FU7dhBO7OSDckmBszJlkxgbF8mrpi9TFmU=,tag:GnoCSNy5a860fhoSy1jA5Q==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  version: 3.8.1
