apiVersion: v1
stringData:
  server_secret: ENC[AES256_GCM,data:LL8dkl509B7hoe55yhw=,iv:qnmYh6+fkl3YWi6kzLQs/FA10BijGw/BVhb/dvTMS7s=,tag:Oi9LcnxlkQb1KT4bJ4rMzA==,type:str]
  y_provider_api_key: ENC[AES256_GCM,data:QyqJ0u96ampxOC3unpul0XDfKhEn6Ngsknkt,iv:h670CY9MKlkrbsRRzBYrmfEYfTq36TifqMxRu03FW3k=,tag:1U0muUA3UyN8BVQva61m8w==,type:str]
  django_secret: ENC[AES256_GCM,data:GubHTYBAxKdtamsV,iv:Vh7i4Ibyq9wIsJ5cHePhoAn2ZHl5EvapMKyB0DQCr18=,tag:KQkZcigtRAyfvSY6hGJjHw==,type:str]
  server_api_token: ENC[AES256_GCM,data:VepZrmZn214RuF/AWqDSmN9CbXqUHw==,iv:gq7LUhrDl93hQAJm46lXevWpRVigbi+jUfjBoqJmd+8=,tag:/W30zZjeNbPHWn5Q8YRi6Q==,type:str]
  superuser_password: ENC[AES256_GCM,data:dL1knKA=,iv:lxh53I7JnoRBgv+Gp147/5UrSE5q6IX/Ufc73CRTLLg=,tag:ghPNwOBrjL+WEifsyLG8Wg==,type:str]
  oidc_secret: ENC[AES256_GCM,data:WU6KMw7hzRZuxk+8+L9f42vCzm4o/JLcUlsBXnS7Mr8=,iv:WYrWJSrXLvnZFmL9NxhyC+TsoTEDmJ45/zjlyPhmpHo=,tag:CpiowdtECRlUL/0xoxvzxQ==,type:str]
kind: Secret
metadata:
  name: sec-docs
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1xqm6rlmcsyfna0chsmf8gw64n86405rgr04ek5drad04ca00fewqp02n5c
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZcVFSWFZwSUNrUzNWS2w0
        RnRPTHgwdGF4UE5USVlQc1RvT1Z0SDJ1eUdnCk5HQzJpZ3dGUU0xM01MK3VTTkpF
        ZUZ4Q1NBZHVKanVadVFwMzZzVklVQncKLS0tIDB5dzYvSFZEbll3Sld2clIzM1lK
        aGR2T05QcGpHa3cyRXpyY3hqMWFRZDQK0+Cwyugs35u+exKkkmh9qvV1Hbdnn7X7
        69GyaoVnPMBLeTuzfPT3QC+v8dsSO+EOGmdSFhWovGK6VTOLPl2mlg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2024-12-23T21:51:16Z"
  mac: ENC[AES256_GCM,data:3tzV0uJjD1B5bSJd+H5Bc417EUMTsV+kgb31wZbS+xllgoJkG1sMPKb31J9cXUD7W7KN1EIZs1g5PXWxhniR0askTts8mIH8H29cM2kSOrvEbS4aquc74ZFT0Z80iKSrVy5bhDMHSm98fF0HDvIHmbe1YjsLrsqS1JhP60zNzsA=,iv:6yvVki6WnCqt+t0DJDYEJzA1f8tKJW4Lemk/Ukcni6Q=,tag:jWYOrL0HKNYEkQkoAewASQ==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  version: 3.8.1
